import { env } from 'cloudflare:workers';

let initialized = false;

export async function ensureDatabase() {
  if (initialized) return;
  await env.DB.batch([
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS work_reports (
      id TEXT PRIMARY KEY NOT NULL,
      report_number TEXT,
      owner_id TEXT NOT NULL,
      status TEXT DEFAULT 'draft' NOT NULL,
      customer_id TEXT NOT NULL,
      customer_company TEXT DEFAULT '' NOT NULL,
      customer_name TEXT DEFAULT '' NOT NULL,
      customer_email TEXT DEFAULT '' NOT NULL,
      customer_address TEXT DEFAULT '' NOT NULL,
      work_date TEXT NOT NULL,
      work_address TEXT DEFAULT '' NOT NULL,
      work_minutes INTEGER DEFAULT 0 NOT NULL,
      drive_minutes INTEGER DEFAULT 0 NOT NULL,
      distance_km REAL DEFAULT 0 NOT NULL,
      work_description TEXT DEFAULT '' NOT NULL,
      findings TEXT DEFAULT '' NOT NULL,
      complaints TEXT DEFAULT '' NOT NULL,
      recommendations TEXT DEFAULT '' NOT NULL,
      internal_notes TEXT DEFAULT '' NOT NULL,
      personnel_json TEXT DEFAULT '[]' NOT NULL,
      positions_json TEXT DEFAULT '[]' NOT NULL,
      signer_name TEXT DEFAULT '' NOT NULL,
      signature_key TEXT,
      pdf_key TEXT,
      sent_to TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    )`),
    env.DB.prepare('CREATE UNIQUE INDEX IF NOT EXISTS idx_work_reports_number ON work_reports(report_number)'),
    env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_work_reports_owner_updated ON work_reports(owner_id, updated_at)'),
    env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_work_reports_customer ON work_reports(customer_id)'),
    env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_work_reports_status ON work_reports(status)'),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS personnel_preferences (
      owner_id TEXT PRIMARY KEY NOT NULL,
      employee_name TEXT DEFAULT '' NOT NULL,
      role TEXT DEFAULT 'Kältemechatroniker' NOT NULL,
      updated_at TEXT NOT NULL
    )`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS app_users (
      id TEXT PRIMARY KEY NOT NULL,
      name TEXT NOT NULL COLLATE NOCASE,
      job_role TEXT DEFAULT 'Kältemechatroniker' NOT NULL,
      pin_hash TEXT NOT NULL,
      pin_salt TEXT NOT NULL,
      active INTEGER DEFAULT 1 NOT NULL,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    )`),
    env.DB.prepare('CREATE UNIQUE INDEX IF NOT EXISTS idx_app_users_name ON app_users(name COLLATE NOCASE)'),
    env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_app_users_active_name ON app_users(active, name)'),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS auth_attempts (
      attempt_key TEXT PRIMARY KEY NOT NULL,
      attempts INTEGER DEFAULT 0 NOT NULL,
      window_started TEXT NOT NULL,
      locked_until TEXT
    )`),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS report_additions (
      id TEXT PRIMARY KEY NOT NULL,
      report_id TEXT NOT NULL,
      quantity REAL DEFAULT 1 NOT NULL,
      unit TEXT DEFAULT 'Stück' NOT NULL,
      title TEXT NOT NULL,
      item_id TEXT,
      variation_id TEXT,
      reason TEXT DEFAULT '' NOT NULL,
      added_by TEXT NOT NULL,
      created_at TEXT NOT NULL
    )`),
    env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_report_additions_report ON report_additions(report_id, created_at)'),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS plenty_order_drafts (
      report_id TEXT PRIMARY KEY NOT NULL,
      status TEXT DEFAULT 'draft' NOT NULL,
      customer_reference TEXT DEFAULT '' NOT NULL,
      billing_address_json TEXT DEFAULT '{}' NOT NULL,
      delivery_same_as_billing INTEGER DEFAULT 1 NOT NULL,
      delivery_address_json TEXT DEFAULT '{}' NOT NULL,
      positions_json TEXT DEFAULT '[]' NOT NULL,
      plenty_order_id TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    )`),
    env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_plenty_order_drafts_status_updated ON plenty_order_drafts(status, updated_at)'),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS crm_leads (
      id TEXT PRIMARY KEY NOT NULL,
      source TEXT DEFAULT 'Manuell' NOT NULL,
      source_reference TEXT,
      incoming_at TEXT NOT NULL,
      status TEXT DEFAULT 'Neu' NOT NULL,
      priority TEXT DEFAULT 'Normal' NOT NULL,
      tags_json TEXT DEFAULT '[]' NOT NULL,
      internal_notes TEXT DEFAULT '' NOT NULL,
      appointment_at TEXT,
      assignee TEXT DEFAULT '' NOT NULL,
      first_name TEXT DEFAULT '' NOT NULL,
      last_name TEXT DEFAULT '' NOT NULL,
      company TEXT DEFAULT '' NOT NULL,
      phone TEXT DEFAULT '' NOT NULL,
      phone_normalized TEXT DEFAULT '' NOT NULL,
      email TEXT DEFAULT '' NOT NULL,
      email_normalized TEXT DEFAULT '' NOT NULL,
      name_normalized TEXT DEFAULT '' NOT NULL,
      street TEXT DEFAULT '' NOT NULL,
      house_number TEXT DEFAULT '' NOT NULL,
      zip TEXT DEFAULT '' NOT NULL,
      city TEXT DEFAULT '' NOT NULL,
      interest TEXT DEFAULT '' NOT NULL,
      manufacturer TEXT DEFAULT '' NOT NULL,
      rooms TEXT DEFAULT '' NOT NULL,
      area TEXT DEFAULT '' NOT NULL,
      summary TEXT DEFAULT '' NOT NULL,
      contact_count INTEGER DEFAULT 1 NOT NULL,
      last_contact_at TEXT NOT NULL,
      google_contact_id TEXT,
      google_exported_at TEXT,
      google_export_error TEXT,
      plenty_contact_id TEXT,
      plenty_customer_number TEXT,
      plenty_address_id TEXT,
      plenty_exported_at TEXT,
      plenty_export_error TEXT,
      created_by TEXT NOT NULL,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL
    )`),
    env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_crm_leads_status_contact ON crm_leads(status, last_contact_at)'),
    env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_crm_leads_phone ON crm_leads(phone_normalized)'),
    env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_crm_leads_email ON crm_leads(email_normalized)'),
    env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_crm_leads_name ON crm_leads(name_normalized)'),
    env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_crm_leads_assignee ON crm_leads(assignee)'),
    env.DB.prepare(`CREATE TABLE IF NOT EXISTS crm_lead_events (
      id TEXT PRIMARY KEY NOT NULL,
      lead_id TEXT NOT NULL,
      occurred_at TEXT NOT NULL,
      channel TEXT DEFAULT 'Notiz' NOT NULL,
      note TEXT NOT NULL,
      created_by TEXT NOT NULL,
      created_at TEXT NOT NULL
    )`),
    env.DB.prepare('CREATE INDEX IF NOT EXISTS idx_crm_lead_events_lead_time ON crm_lead_events(lead_id, occurred_at)'),
    env.DB.prepare('PRAGMA optimize'),
  ]);
  const crmColumns = await env.DB.prepare('PRAGMA table_info(crm_leads)').all<{ name: string }>();
  if (!(crmColumns.results ?? []).some((column) => column.name === 'plenty_customer_number')) {
    await env.DB.prepare('ALTER TABLE crm_leads ADD COLUMN plenty_customer_number TEXT').run();
  }
  initialized = true;
}
